### ISSUE TITLE
TODO: Pending List

### ISSUE THREAD

**Issue by vorasmit** [resilient-tech/india-compliance#82]
- [x] `is_reverse_charge` to hide and unhide instead of delete
- [x] Validations for Sales Order / Delivery Note / Sales Invoice in Sync with each other
- [ ] State Autocomplete for Quick Entry Dialog (Party and Address)
- [x] Improve Address Split
- [x] remove report GSTR2
